"""
Multi-stage blocking (candidate generation).

Comparing every Source-1 record against every Source-2/Source-3 record is
O(n*m) and unnecessary. Instead we build several cheap inverted indexes over
Source-2/Source-3 records (by country, by name token, by address token, by
character n-gram, by postal code) and, for each Source-1 record, take the
UNION of everything any single rule retrieves. This favors high recall
(a pair generated by ANY reasonable rule is kept) while still pruning the
overwhelming majority of impossible pairs.

If, after the union, an entity still has more candidates than
MAX_CANDIDATES_PER_ENTITY, we keep the highest-scoring ones (score = number
of independent blocking rules that fired for that candidate), so the cap
does not arbitrarily drop clearly-related candidates.
"""
from __future__ import annotations

import logging
from collections import defaultdict
from typing import Iterable

import pandas as pd

from src import config

logger = logging.getLogger(__name__)


def _tokenize(text: str) -> set[str]:
    if not text:
        return set()
    return {t for t in text.split(" ") if len(t) >= config.MIN_TOKEN_LENGTH}


def _char_ngrams(text: str, n: int = config.NGRAM_SIZE) -> set[str]:
    compact = text.replace(" ", "")
    if len(compact) < n:
        return {compact} if compact else set()
    return {compact[i : i + n] for i in range(len(compact) - n + 1)}


class BlockingIndex:
    """Inverted indexes built once over the S2/S3 candidate pool."""

    def __init__(self, candidates_df: pd.DataFrame):
        """
        candidates_df: normalized Source-2 + Source-3 records concatenated,
        must contain entity_id, normalized_business_name,
        normalized_business_address, normalized_country, postal_code.
        """
        self.df = candidates_df.reset_index(drop=True)
        self.by_country: dict[str, set[str]] = defaultdict(set)
        self.by_name_token: dict[str, set[str]] = defaultdict(set)
        self.by_addr_token: dict[str, set[str]] = defaultdict(set)
        self.by_name_ngram: dict[str, set[str]] = defaultdict(set)
        self.by_postal: dict[str, set[str]] = defaultdict(set)

        self._build()

    def _build(self) -> None:
        for row in self.df.itertuples(index=False):
            eid = row.entity_id
            country = row.normalized_country
            name = row.normalized_business_name
            addr = row.normalized_business_address
            postal = row.postal_code

            if country:
                self.by_country[country].add(eid)
            for tok in _tokenize(name):
                self.by_name_token[tok].add(eid)
            for tok in _tokenize(addr):
                self.by_addr_token[tok].add(eid)
            for gram in _char_ngrams(name):
                self.by_name_ngram[gram].add(eid)
            if postal:
                self.by_postal[postal].add(eid)

        logger.info(
            "Built blocking index over %d candidate records "
            "(%d countries, %d name tokens, %d address tokens, "
            "%d name n-grams, %d postal codes)",
            len(self.df), len(self.by_country), len(self.by_name_token),
            len(self.by_addr_token), len(self.by_name_ngram), len(self.by_postal),
        )

    def get_candidates_with_scores(self, s1_row) -> dict[str, int]:
        """
        Return {candidate_entity_id: rule_hit_count} for a single Source-1
        row (a namedtuple from itertuples), using the union of every rule.
        """
        scores: dict[str, int] = defaultdict(int)

        country = s1_row.normalized_country
        if country and country in self.by_country:
            for eid in self.by_country[country]:
                scores[eid] += 1

        for tok in _tokenize(s1_row.normalized_business_name):
            for eid in self.by_name_token.get(tok, ()):
                scores[eid] += 1

        for tok in _tokenize(s1_row.normalized_business_address):
            for eid in self.by_addr_token.get(tok, ()):
                scores[eid] += 1

        for gram in _char_ngrams(s1_row.normalized_business_name):
            for eid in self.by_name_ngram.get(gram, ()):
                scores[eid] += 1

        postal = s1_row.postal_code
        if postal and postal in self.by_postal:
            for eid in self.by_postal[postal]:
                scores[eid] += 3  # postal match is a strong, low-noise signal

        return scores


def generate_candidates(
    source1_df: pd.DataFrame,
    source2_df: pd.DataFrame,
    source3_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Generate blocking candidates for every Source-1 record.

    Returns a DataFrame with columns:
        source1_entity_id, candidate_entity_ids (list[str])
    Every Source-1 entity gets exactly one row, even with an empty list.
    Only S2/S3 IDs appear as candidates; duplicates are removed.
    """
    pool_cols = [
        "entity_id", "normalized_business_name",
        "normalized_business_address", "normalized_country", "postal_code",
    ]
    candidate_pool = pd.concat(
        [source2_df[pool_cols], source3_df[pool_cols]], ignore_index=True
    )
    # Guard against a candidate pool containing S1 IDs by mistake.
    candidate_pool = candidate_pool[
        ~candidate_pool["entity_id"].astype(str).str.startswith("S1-")
    ]

    index = BlockingIndex(candidate_pool)

    rows = []
    total_candidates = 0
    for s1_row in source1_df.itertuples(index=False):
        scores = index.get_candidates_with_scores(s1_row)
        # Never let an S1 id slip in as its own candidate.
        scores.pop(s1_row.entity_id, None)

        if len(scores) > config.MAX_CANDIDATES_PER_ENTITY:
            ranked = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)
            kept_ids = [eid for eid, _ in ranked[: config.MAX_CANDIDATES_PER_ENTITY]]
        else:
            kept_ids = list(scores.keys())

        kept_ids = sorted(set(kept_ids))  # de-dupe, deterministic order
        total_candidates += len(kept_ids)
        rows.append({"source1_entity_id": s1_row.entity_id, "candidate_entity_ids": kept_ids})

    result = pd.DataFrame(rows, columns=["source1_entity_id", "candidate_entity_ids"])
    avg_candidates = total_candidates / len(result) if len(result) else 0.0
    logger.info(
        "Generated candidates for %d Source-1 entities (avg %.1f candidates/entity, "
        "%d total pairs)",
        len(result), avg_candidates, total_candidates,
    )
    return result


def explode_candidate_pairs(candidates_df: pd.DataFrame) -> pd.DataFrame:
    """
    Turn the one-row-per-S1-entity candidate table into a flat pair table:
    columns source1_entity_id, candidate_entity_id (one row per pair).
    Entities with zero candidates simply contribute zero rows here.
    """
    exploded = candidates_df.explode("candidate_entity_ids")
    exploded = exploded.rename(columns={"candidate_entity_ids": "candidate_entity_id"})
    exploded = exploded.dropna(subset=["candidate_entity_id"])
    return exploded.reset_index(drop=True)
